name: '"Configure AWS Credentials" Action For GitHub Actions'
description: 'Configure AWS credential and region environment variables for use with the AWS CLI and AWS SDKs'
inputs:
  audience:
    default: 'sts.amazonaws.com'
    description: 'The audience to use for the OIDC provider'
    required: true
outputs:
  aws-account-id:
    description: 'The AWS account ID for the provided credentials'
runs:
  using: 'node12'
  main: 'handler.js'
