name: '"Configure AWS Credentials" Action For GitHub Actions'
description: 'Configure AWS credential and region environment variables for use with the AWS CLI and AWS SDKs'
inputs:
  audience:
    default: 'sts.amazonaws.com'
    description: 'The audience to use for the OIDC provider'
    required: true
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: true
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: false
  role-session-name:
    description: 'Role session name (default: GitHubActions)'
    required: false
outputs:
  aws-account-id:
    description: 'The AWS account ID for the provided credentials'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
